### PR TITLE
OCW-651: Sphinx: Show Line Numbers on source code highlighing

### PR DESCRIPTION
**Pull request by REDucka**
- add :linenos: for code blocks php, html, json, yaml, javascripts

### CODE REVIEW

**Comment by xabbuh** [comment]
The drawback of this approach is that you need to remember to add the `:linenos:` option for each new code block. IIRC, there is a way to control this behaviour on the global level. What do you think of using such an approach instead?

**Comment by DimaSoroka** [comment]
The only thing us that not all code blocks will need to have line numbers.

**Comment by mbessolov** [comment]
@xabbuh I do not see a global configuration option that would allow to do that, and a quick dive into sphynx and pygments code didn't reveal anything like that either.

I would appreciate if you can share any more hints.

The best we could do was to create a sphinx extension that introduces such a global configuration option. We can add this extension and enable it in conf.py if it would work better than manually adding :linenos: for individual codeblocks.

**Comment by mbessolov** [comment]
I'll pull the PR with that extension from the internal repository once confirmed with the team that documentation generation for orocrm.com is not affected by the changes.

**Pull request merged**
